version: '3'
services:
  db:
    image: surrealdb/surrealdb:1.0.0
    command: start --log debug --user root --pass root memory --allow-scripting
  backend:
    image: xilefmusics/money-app:latest
  proxauth:
    image: xilefmusics/proxauth:0.1.0
    environment:
      CONFIG: |
        users:
        - username: test
          password: 5fa96090628b61ce59ce0a40b30710c584c8d294885ea0dfbaf491ed8970d9f4
          salt: 11463a4a-9f9c-4e17-bd05-96ebc1a68277
        rules:
        - toHost: backend
          toPort: 8000
          allowedUsers: [test]
          redirectToLogin: true
          backgroundColor: "#1e1e1e"
          textColor: "#BCBCBC"
          primaryColor: "#bb0000"
          title: "Money-App"
    ports:
    - 8080:8080
