users:
- username: test
  password: 5fa96090628b61ce59ce0a40b30710c584c8d294885ea0dfbaf491ed8970d9f4
  salt: 11463a4a-9f9c-4e17-bd05-96ebc1a68277

rules:
- toPort: 8082
  fromPath: "/api"
  toPath: "/api"
  allowedUsers: [test]
  backgroundColor: "#1e1e1e"
  textColor: "#BCBCBC"
  primaryColor: "#bb0000"
  title: "Money-App"
- toPort: 8080
  allowedUsers: [test]
  redirectToLogin: true
  backgroundColor: "#1e1e1e"
  textColor: "#BCBCBC"
  primaryColor: "#bb0000"
  title: "Money-App"
