services:
  db:
    image: surrealdb/surrealdb:v1.5.4-dev
    command: start --log debug --user root --pass root memory --allow-scripting

  backend:
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    working_dir: /app/src/money_app/backend
    command: cargo watch -cqx run
    environment:
      DB_HOST: db
    volumes:
    - ..:/app/src/money_app
    - ../../fancy_surreal:/app/src/fancy_surreal

  frontend:
    build:
      context: .
      dockerfile: ./frontend.Dockerfile
    working_dir: /app/src/money_app/frontend
    command: trunk serve --address 0.0.0.0
    volumes:
    - ..:/app/src/money_app
    - ../../fancy_yew:/app/src/fancy_yew

  proxauth:
    image: xilefmusics/proxauth:0.1.0
    environment:
      CONFIG: |
        users:
        - username: test
          password: 5fa96090628b61ce59ce0a40b30710c584c8d294885ea0dfbaf491ed8970d9f4
          salt: 11463a4a-9f9c-4e17-bd05-96ebc1a68277
        rules:
        - toHost: backend
          toPort: 8082
          fromPath: "/api"
          toPath: "/api"
          allowedUsers: [test]
          backgroundColor: "#1e1e1e"
          textColor: "#ebdbb2"
          primaryColor: "#cc241d"
          title: "Worship Viewer"
        - toHost: frontend
          toPort: 8080
          allowedUsers: [test]
          redirectToLogin: true
          backgroundColor: "#1e1e1e"
          textColor: "#ebdbb2"
          primaryColor: "#cc241d"
          title: "Worship Viewer"
    ports:
    - 8080:8080
